DECLARE
OID_JUAN INTEGER;
OID_JOSE INTEGER;
OID_MATILDE INTEGER;
OID_LUISA INTEGER;

OID_DICK INTEGER;
OID_CLARKE INTEGER;

OID_ANDROIDE INTEGER;
OID_CASTILLO INTEGER;
OID_ODISEA INTEGER;
OID_CENTINELA INTEGER;
OID_RAMA INTEGER;

BEGIN

INSERTAR_AUTOR('Philip K.','Dick'); 
INSERTAR_LIBRO('¿Sueñan los androides con ovejas eléctricas?');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_DICK FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_ANDROIDE FROM DUAL;
INSERTAR_AUTORIA(OID_DICK,OID_ANDROIDE);

INSERTAR_LIBRO('El hombre del castillo');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_CASTILLO FROM DUAL;
INSERTAR_AUTORIA(OID_DICK,OID_CASTILLO);

INSERTAR_AUTOR('Arthur C.','Clarke');
INSERTAR_LIBRO('2001 Una odisea espacial');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_CLARKE FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_ODISEA FROM DUAL;
INSERTAR_AUTORIA(OID_CLARKE,OID_ODISEA);

INSERTAR_LIBRO('El centinela');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_CENTINELA FROM DUAL;
INSERTAR_AUTORIA(OID_CLARKE,OID_CENTINELA);

INSERTAR_LIBRO('Cita con Rama');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_RAMA FROM DUAL;
INSERTAR_AUTORIA(OID_CLARKE,OID_RAMA);


INSERTAR_USUARIO('11111111A','Juan','Pérez Martín','1/1/1980', 'juan@us.es', 'qwerty', 'PAS' );
OID_JUAN := SEC_USUARIOS_OID.CURRVAL;
INSERTAR_USUARIO('11111112B','Josefa','López Consuegra','1/1/1980', 'josefa@us.es', '123456', 'PDI' );
OID_JOSE := SEC_USUARIOS_OID.CURRVAL;
INSERTAR_USUARIO('11111113C','Matilde','Arjona Gómez','1/1/1980', 'matilde@us.es', 'matilde', 'ALUMNO' );
OID_MATILDE := SEC_USUARIOS_OID.CURRVAL;
INSERTAR_USUARIO('11111114D','Luisa','García Marín','1/1/1980', 'luisa@us.es', 'qwerty', 'PDI' );
OID_LUISA := SEC_USUARIOS_OID.CURRVAL;
COMMIT;

END;
