DECLARE
OID_DICK INTEGER;
OID_CLARKE INTEGER;
OID_LESSING INTEGER;
OID_LEM INTEGER;
OID_BRADBURY INTEGER;
OID_ASIMOV INTEGER;
OID_HERBERT INTEGER;
OID_SAGAN INTEGER;
OID_GIBSON INTEGER;
OID_SIMMONS INTEGER;
OID_CARD INTEGER;
OID_ADAMS INTEGER;
OID_SIMAK INTEGER;
OID_NIVEN INTEGER;
OID_FORWARD INTEGER;
OID_STAPLEDON INTEGER;
OID_VERNE INTEGER;
OID_BRESTER INTEGER;
OID_VANCE INTEGER;
OID_ORWELL INTEGER;
OID_WELLS INTEGER;
OID_BESTER INTEGER;
OID_STOKER INTEGER;
OID_FOLLET INTEGER;
OID_GORDON INTEGER;
OID_LORCA INTEGER;
OID_SARAMAGO INTEGER;
OID_TOOLE INTEGER;

OID_ANDROIDE INTEGER;
OID_CASTILLO INTEGER;
OID_ODISEA INTEGER;
OID_CENTINELA INTEGER;
OID_RAMA INTEGER;
OID_CRONICAS INTEGER;
OID_SOLARIS INTEGER;
OID_FUNDACION INTEGER;
OID_ROBOT INTEGER;
OID_CANOPUS INTEGER;
OID_DUNE INTEGER;
OID_FIASCO INTEGER;
OID_FAHRENHEIT INTEGER;
OID_CONTACT INTEGER;
OID_VALIS INTEGER;
OID_NEUROMANTE INTEGER;
OID_HYPERION INTEGER;
OID_ENDER INTEGER;
OID_DIOSES INTEGER;
OID_CIBERIADA INTEGER;
OID_INFANCIA INTEGER;
OID_AUTOESTOPISTA INTEGER;
OID_TRANSITO INTEGER;
OID_MUNDOANILLO INTEGER;
OID_INVENCIBLE INTEGER;
OID_DRAGON INTEGER;
OID_UBIK INTEGER;
OID_SIRIO INTEGER;
OID_20000 INTEGER;
OID_ETERNIDAD INTEGER;
OID_ESTRELLAS INTEGER;
OID_TSCHAI INTEGER;
OID_DIARIOS INTEGER;
OID_1984 INTEGER;
OID_MAQUINA INTEGER;
OID_GUERRA INTEGER;
OID_CANTICOS INTEGER;
OID_FABULAS INTEGER;
OID_FERIA INTEGER;
OID_PAJA INTEGER;
OID_MUERTOS INTEGER;
OID_LUNA INTEGER;
OID_ISLA INTEGER;
OID_VUELTA INTEGER;
OID_GRANT INTEGER;
OID_DRAC INTEGER;
OID_PILARES INTEGER;
OID_CAIDA INTEGER;
OID_INVIERNO INTEGER;
OID_UMBRAL INTEGER;
OID_MEDICO INTEGER;
OID_NY INTEGER;
OID_CEGUERA INTEGER;
OID_MUERTE INTEGER;
OID_CONJURA INTEGER;

BEGIN

INSERTAR_AUTOR('Philip K.','Dick'); 
INSERTAR_LIBRO('¿Sueñan los androides con ovejas eléctricas?');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_DICK FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_ANDROIDE FROM DUAL;
INSERTAR_AUTORIA(OID_DICK,OID_ANDROIDE);

INSERTAR_LIBRO('El hombre del castillo');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_CASTILLO FROM DUAL;
INSERTAR_AUTORIA(OID_DICK,OID_CASTILLO);

INSERTAR_AUTOR('Arthur C.','Clarke');
INSERTAR_LIBRO('2001 Una odisea espacial');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_CLARKE FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_ODISEA FROM DUAL;
INSERTAR_AUTORIA(OID_CLARKE,OID_ODISEA);

INSERTAR_LIBRO('El centinela');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_CENTINELA FROM DUAL;
INSERTAR_AUTORIA(OID_CLARKE,OID_CENTINELA);

INSERTAR_LIBRO('Cita con Rama');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_RAMA FROM DUAL;
INSERTAR_AUTORIA(OID_CLARKE,OID_RAMA);


INSERTAR_AUTOR('Doris','Lessing');
INSERTAR_LIBRO('Canopus in Argos');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_LESSING FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_CANOPUS FROM DUAL;
INSERTAR_AUTORIA(OID_LESSING,OID_CANOPUS);

INSERTAR_AUTOR('Stanislav','Lem');
INSERTAR_LIBRO('Solaris');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_LEM FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_SOLARIS FROM DUAL;
INSERTAR_AUTORIA(OID_LEM,OID_SOLARIS);

INSERTAR_LIBRO('Fiasco');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_FIASCO FROM DUAL;
INSERTAR_AUTORIA(OID_LEM,OID_FIASCO);

INSERTAR_LIBRO('Ciberiada');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_CIBERIADA FROM DUAL;
INSERTAR_AUTORIA(OID_LEM,OID_CIBERIADA);

INSERTAR_LIBRO('Diarios de las estrellas');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_DIARIOS FROM DUAL;
INSERTAR_AUTORIA(OID_LEM,OID_DIARIOS);

INSERTAR_LIBRO('Fábulas de robots');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_FABULAS FROM DUAL;
INSERTAR_AUTORIA(OID_LEM,OID_FABULAS);

INSERTAR_AUTOR('Ray','Bradbury');
INSERTAR_LIBRO('Las crónicas marcianas');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_BRADBURY FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_CRONICAS FROM DUAL;
INSERTAR_AUTORIA(OID_BRADBURY,OID_CRONICAS);

INSERTAR_LIBRO('Fahrenheit 451');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_FAHRENHEIT FROM DUAL;
INSERTAR_AUTORIA(OID_BRADBURY,OID_FAHRENHEIT);

INSERTAR_LIBRO('La feria de las tinieblas');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_FERIA FROM DUAL;
INSERTAR_AUTORIA(OID_BRADBURY,OID_FERIA);

INSERTAR_AUTOR('Isaac','Asimov');
INSERTAR_LIBRO('Fundación');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_ASIMOV FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_FUNDACION FROM DUAL;
INSERTAR_AUTORIA(OID_ASIMOV,OID_FUNDACION);

INSERTAR_LIBRO('Yo, Robot');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_ROBOT FROM DUAL;
INSERTAR_AUTORIA(OID_ASIMOV,OID_ROBOT);

INSERTAR_LIBRO('Los propios dioses');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_DIOSES FROM DUAL;
INSERTAR_AUTORIA(OID_ASIMOV,OID_DIOSES);

INSERTAR_LIBRO('El fin de la eternidad');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_ETERNIDAD FROM DUAL;
INSERTAR_AUTORIA(OID_ASIMOV,OID_ETERNIDAD);

INSERTAR_AUTOR('Julio','Verne');
INSERTAR_LIBRO('20000 leguas de viaje submarino');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_VERNE FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_20000 FROM DUAL;
INSERTAR_AUTORIA(OID_VERNE,OID_20000);

INSERTAR_LIBRO('De la Tierra a la Luna');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_LUNA FROM DUAL;
INSERTAR_AUTORIA(OID_VERNE,OID_LUNA);

INSERTAR_LIBRO('La isla Misteriosa');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_ISLA FROM DUAL;
INSERTAR_AUTORIA(OID_VERNE,OID_ISLA);

INSERTAR_LIBRO('La vuelta al mundo en 80 días');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_VUELTA FROM DUAL;
INSERTAR_AUTORIA(OID_VERNE,OID_VUELTA);

INSERTAR_LIBRO('Los hijos del capitán Grant');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_GRANT FROM DUAL;
INSERTAR_AUTORIA(OID_VERNE,OID_GRANT);

INSERTAR_AUTOR('George','Orwell');
INSERTAR_LIBRO('1984');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_ORWELL FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_1984 FROM DUAL;
INSERTAR_AUTORIA(OID_ORWELL,OID_1984);

INSERTAR_AUTOR('Herbert G.','Wells');
INSERTAR_LIBRO('La máquina del tiempo');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_WELLS FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_MAQUINA FROM DUAL;
INSERTAR_AUTORIA(OID_WELLS,OID_MAQUINA);

INSERTAR_LIBRO('La guerra de los mundos');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_GUERRA FROM DUAL;
INSERTAR_AUTORIA(OID_WELLS,OID_GUERRA);

INSERTAR_AUTOR('Alfred','Bester');
INSERTAR_LIBRO('La estrellas de mi destino');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_BESTER FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_ESTRELLAS FROM DUAL;
INSERTAR_AUTORIA(OID_BESTER,OID_ESTRELLAS);

INSERTAR_AUTOR('Fran','Herbert');
INSERTAR_LIBRO('Dune');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_HERBERT FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_DUNE FROM DUAL;
INSERTAR_AUTORIA(OID_HERBERT,OID_DUNE);

INSERTAR_AUTOR('Douglas','Adams');
INSERTAR_LIBRO('La guía del autoestopista galáctico');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_ADAMS FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_AUTOESTOPISTA FROM DUAL;
INSERTAR_AUTORIA(OID_ADAMS,OID_AUTOESTOPISTA);

INSERTAR_AUTOR('Jack','Vance');
INSERTAR_LIBRO('Ciclo de Tschai');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_VANCE FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_TSCHAI FROM DUAL;
INSERTAR_AUTORIA(OID_VANCE,OID_TSCHAI);

INSERTAR_AUTOR('Olaf','Stapledon');
INSERTAR_LIBRO('Sirio');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_STAPLEDON FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_SIRIO FROM DUAL;
INSERTAR_AUTORIA(OID_STAPLEDON,OID_SIRIO);

INSERTAR_AUTOR('Robert L.','Forward');
INSERTAR_LIBRO('Huevo de dragón');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_FORWARD FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_DRAGON FROM DUAL;
INSERTAR_AUTORIA(OID_FORWARD,OID_DRAGON);

INSERTAR_AUTOR('Larry','Niven');
INSERTAR_LIBRO('Mundoanillo');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_NIVEN FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_MUNDOANILLO FROM DUAL;
INSERTAR_AUTORIA(OID_NIVEN,OID_MUNDOANILLO);

INSERTAR_LIBRO('La paja en el ojo de dios');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_PAJA FROM DUAL;
INSERTAR_AUTORIA(OID_NIVEN,OID_PAJA);

INSERTAR_AUTOR('Clifford D.','Simak');
INSERTAR_LIBRO('Estación de tránsito');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_SIMAK FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_TRANSITO FROM DUAL;
INSERTAR_AUTORIA(OID_SIMAK,OID_TRANSITO);

INSERTAR_AUTOR('Carl','Sagan');
INSERTAR_LIBRO('Contact');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_SAGAN FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_CONTACT FROM DUAL;
INSERTAR_AUTORIA(OID_SAGAN,OID_CONTACT);

INSERTAR_AUTOR('William','Gibson');
INSERTAR_LIBRO('Neuromante');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_GIBSON FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_NEUROMANTE FROM DUAL;
INSERTAR_AUTORIA(OID_GIBSON,OID_NEUROMANTE);

INSERTAR_AUTOR('Dan','Simmons');
INSERTAR_LIBRO('Hyperión');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_SIMMONS FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_HYPERION FROM DUAL;
INSERTAR_AUTORIA(OID_SIMMONS,OID_HYPERION);

INSERTAR_AUTOR('Orson S.','Card');
INSERTAR_LIBRO('El juego de Ender');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_CARD FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_ENDER FROM DUAL;
INSERTAR_AUTORIA(OID_CARD,OID_ENDER);

INSERTAR_LIBRO('La voz de los muertos');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_MUERTOS FROM DUAL;
INSERTAR_AUTORIA(OID_CARD,OID_MUERTOS);

INSERTAR_AUTOR('Bram', 'Stoker');
INSERTAR_LIBRO('Drácula');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_STOKER FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_DRAC FROM DUAL;
INSERTAR_AUTORIA(OID_STOKER,OID_DRAC);

INSERTAR_AUTOR('Ken', 'Follet');
INSERTAR_LIBRO('Los pilares de la tierra');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_FOLLET FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_PILARES FROM DUAL;
INSERTAR_AUTORIA(OID_FOLLET,OID_PILARES);

INSERTAR_LIBRO('La caída de los gigantes');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_CAIDA FROM DUAL;
INSERTAR_AUTORIA(OID_FOLLET,OID_CAIDA);

INSERTAR_LIBRO('El invierno del mundo');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_INVIERNO FROM DUAL;
INSERTAR_AUTORIA(OID_FOLLET,OID_INVIERNO);

INSERTAR_LIBRO('El umbral de la eternidad');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_UMBRAL FROM DUAL;
INSERTAR_AUTORIA(OID_FOLLET,OID_UMBRAL);

INSERTAR_AUTOR('Federico', 'García Lorca');
INSERTAR_LIBRO('Poeta en Nueva York');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_LORCA FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_NY FROM DUAL;
INSERTAR_AUTORIA(OID_LORCA,OID_NY);

INSERTAR_AUTOR('José', 'Saramago');
INSERTAR_LIBRO('Ensayo sobre la ceguera');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_SARAMAGO FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_CEGUERA FROM DUAL;
INSERTAR_AUTORIA(OID_SARAMAGO,OID_CEGUERA);

INSERTAR_LIBRO('Las intermitencias de la muerte');
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_MUERTE FROM DUAL;
INSERTAR_AUTORIA(OID_SARAMAGO,OID_MUERTE);

INSERTAR_AUTOR('Noah', 'Gordon');
INSERTAR_LIBRO('El médico');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_GORDON FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_MEDICO FROM DUAL;
INSERTAR_AUTORIA(OID_SARAMAGO,OID_CEGUERA);

INSERTAR_AUTOR('John K.', 'Toole');
INSERTAR_LIBRO('La Conjura de los necios');
SELECT SEC_AUTORES_OID.CURRVAL INTO OID_TOOLE FROM DUAL;
SELECT SEC_LIBROS_OID.CURRVAL INTO OID_CONJURA FROM DUAL;
INSERTAR_AUTORIA(OID_TOOLE,OID_CONJURA);

COMMIT;

END;
